ministryofjustice/prisoner-content-hub-frontend

.circleci/config.yml

Before this change, our deployment set looks like this:
```
kubectl -n prisoner-content-hub-staging get deployments
NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
aws-es-proxy                               1/1     1            1           46h
prisoner-content-hub-backend               0/1     1            0           11h
prisoner-content-hub-staging-cookhamwood   0/0     0            0           16h
```
This PR renames the Cookham Wood release, removing `staging`, in order to make it consistent with the other deployments

Remove 'staging' from Cookham Wood release name in Cloud Platform

---

helm_deploy/prisoner-content-hub-frontend/templates/ingress.yaml
helm_deploy/prisoner-content-hub-frontend/values.development.yaml
helm_deploy/prisoner-content-hub-frontend/values.production.yaml
helm_deploy/prisoner-content-hub-frontend/values.staging.yaml

This PR:
- Adds a custom hostname for the frontend
- Refactors the ingress slightly to allow multiple hostnames
We've only added Cookham Wood, but this opens the door to use a single deployment with one hostname per prison

Add custom hostnames

---

helm_deploy/prisoner-content-hub-frontend/values.production.yaml

This PR 
- removes some duplicates config in the ingress which I missed
- defaults the ingress to enabled to simplify config (we enable TLS/ingress in all our CP environments)

fix copy/pasta error and enable TLS by default

---

helm_deploy/prisoner-content-hub-frontend/templates/_helpers.tpl
helm_deploy/prisoner-content-hub-frontend/templates/ingress.yaml
helm_deploy/prisoner-content-hub-frontend/values.development.yaml
helm_deploy/prisoner-content-hub-frontend/values.local.yaml
helm_deploy/prisoner-content-hub-frontend/values.production.yaml
helm_deploy/prisoner-content-hub-frontend/values.staging.yaml

This PR:
- Refactors the ingress to correctly build the hostname from an establishment prefix and one or more environment suffixes
- Removes the hostname helper as it's only used once in another helper.
- Removes redundant `path` entries.
Intent
Before now we've built domain names using `-` for the prefix. Our naming scheme in production is `<establishment>.content-hub.service.justice.gov.uk`, so we need to support both.
An ingress definition in Helm would now look like
```
ingress:
domainPrefix: cookhamwood
ingress:
hosts:
- suffix: .content-hub.prisoner.service.justice.gov.uk
cert_secret: prisoner-content-hub-frontend-certificate
- suffix: -prisoner-content-hub-production.apps.live-1.cloud-platform.service.justice.gov.uk
```

Use host prefix/suffix to build frontend hostname

---

.circleci/config.yml

This PR:
- Adds a gated deployment in the development namespace
- Moves the Azure build steps around so they're all together
You can step through the commits to see the above more clearly split.
Intent:
- To allow us to trivially deploy into the development environment for any branch.
This will overwrite any existing deployment, so there's a couple of caveats:
1. Development can enter a broken state by moving back and forth with backend releases. If/when this happens, we'll restore a known good copy of the database.
2. There's only one active deployment, so this approach won't work well for pull requests, where we often have many. This can easily be solved for the frontend, but for Drupal it's a bit trickier to spin up ephemeral databases.
This PR depends on:

Cloud Platform development preview build

---

helm_deploy/prisoner-content-hub-frontend/values.yaml
server/routes/health.js
server/services/health.js
test/routes/health.spec.js
test/services/healthService.spec.js

- Split health endpoints to supply liveness and readiness
- Refactor naming of things in the health service
- Update Helm values to use new liveness and readiness probes

Refactor health check endpoints

---

helm_deploy/prisoner-content-hub-frontend/values.development.yaml
helm_deploy/prisoner-content-hub-frontend/values.production.yaml
helm_deploy/prisoner-content-hub-frontend/values.staging.yaml
helm_deploy/prisoner-content-hub-frontend/values.yaml

The staging environment is available on the following URLs:
- https://berwyn-prisoner-content-hub-staging.apps.live-1.cloud-platform.service.justice.gov.uk
- https://berwyn-prisoner-content-hub-staging.apps.live-1.cloud-platform.service.justice.gov.uk
- https://berwyn-prisoner-content-hub-staging.apps.live-1.cloud-platform.service.justice.gov.uk
The staging environment is available on the following URLs (note the missing `-` between the prison name and `prisoner`):
- https://berwynprisoner-content-hub-staging.apps.live-1.cloud-platform.service.justice.gov.uk
- https://berwynprisoner-content-hub-staging.apps.live-1.cloud-platform.service.justice.gov.uk
- https://berwynprisoner-content-hub-staging.apps.live-1.cloud-platform.service.justice.gov.uk
This issue doesn't affect the CMS, which is …

Fix staging URLs

---

.circleci/config.yml
helm_deploy/prisoner-content-hub-frontend/secrets.example.yaml
helm_deploy/prisoner-content-hub-frontend/templates/deployment.yaml
package-lock.json
package.json
server.js

Cloud Platform recently set up a Sentry organisation on a paid plan. [Sentry](https://sentry.io/for/node/) allows us to collect, track and notify us about code-level exceptions and events with stack-traces. 
This PR adds Sentry exception collection to the Node frontend. 
The `FRONTEND_SENTRY_DSN` has been added to CircleCI in development/staging/production, so exceptions should start appearing in the [dashboard](https://sentry.io/organizations/ministryofjustice/issues/?project=5377056).
We can test this by triggering an exception in a Kubernetes pod or locally (or just deliberately shipping unstable code 🤪). We should definitely validate that this happens as we expect in Cloud Platform.
This will help us catch exceptions and errors early on, and goes hand-in-hand with the alerting & …

Add Sentry exception logging, to centralise and alert on Node exceptions

---

server/routes/content.js
test/routes/content.spec.js

PDF items were consistantly using relative URLs, this would break when we required absolute URLs, such as using pre-signed S3 links
- Update PDF route to use fixUrlProduction rather than relativeUrlFrom to allow behaviour to be consitant with other media
- Update PDF route to redirect rather than directly stream, as we can go direct to the PDF resource

Fix PDF downloads

---

.circleci/config.yml

- Use parameters.establishment to give a clearer release step in CircleCI

Add establishment name to the 'release to env' step

---

.circleci/config.yml

Looking at a recent build, we can see a few dependencies are duplicated for every namespace we deploy to:
This PR removes the duplicated install of KOPS, kubectl, and helm, shifting them into a single step that gets executed at the beginning of the job.
We may be able to optimise this further, for example I _believe_ the checkout in line 36 could be refactored into a single `checkout` step (e.g. L101).

Remove duplicated kops/kubectl/helm installs in CircleCI

---

.circleci/config.yml

This is a bit of an exploration. The PR:
- Refactors code checkout to occur in the job step
- Uses relative paths to remove the need for a custom checkout location
- [more controversially] uses `matrix` parameterisation to deduplicate the release steps. 
The result (after a bit of jigerry-pokery) is the following, where the job name becomes more meaningful in the UI:

Parameterise CircleCI jobs

---

README.md
helm_deploy/prisoner-content-hub-frontend/values.development.yaml
helm_deploy/prisoner-content-hub-frontend/values.production.yaml
helm_deploy/prisoner-content-hub-frontend/values.staging.yaml
helm_deploy/prisoner-content-hub-frontend/values.yaml

For https://trello.com/c/9w8hYZJQ/1380-add-annotation-to-ingress-controllers.
This PR updates the kubernetes ingress annotation following https://mojdt.slack.com/archives/CH6D099DF/p1598372708002900.
This only applies to non-production environments initially. Once we're ready to roll it out across the board we should probably refactor this to remove the environment-specific annotations into something like:
```
{{- $namespace_name := .Release.Namespace }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
... removed for brevity
{{- with .Values.ingress.annotations }}
annotations:
kubernetes.io/ingress.class: {{ $namespace_name }}
{{- toYaml . | nindent 4 }}
{{- end }}
```

Use namespace-specific nginx for non-production environments.

---

server/repositories/categoryFeaturedContent.js
server/services/hubContent.js
server/views/pages/category.html
test/repositories/categoryFeaturedContentRepository.spec.js
test/routes/content.spec.js
test/services/hubContentService.spec.js

- Renamed relatedContent to categoryFeaturedContent to stop conflicts and misunderstanding

Make landing page content variables sensible

---

helm_deploy/prisoner-content-hub-frontend/values.development.yaml
helm_deploy/prisoner-content-hub-frontend/values.staging.yaml

Following the ingress configuration rollback in Cloud Platform, we need to revert our ingress class back to `nginx`.
See https://mojdt.slack.com/archives/C69NWE339/p1601994739044500?thread_ts=1601994124.044000&cid=C69NWE339

Revert ingress class to 'nginx' 

---

server/repositories/hubContent.js

The fix is this
```
const response = await httpClient.get(endpoint, { query });
```
Originally we were passing the query as the second parameter, which is wrong, it should be wrapped in an object
So `{ _prison: 123 }` becomes `{ query: { _prison: 123 } }`

Fix missing query parameter when calling the Term endpoint

---

assets/javascript/games/crossword/christmas.js
server/routes/games.js
server/views/pages/games/christmas-crossword.html

https://trello.com/c/hADmC1bR/1760-create-christmas-crosswords-schedule-release
Added the route `/games/christmas-crossword` and applied the initial list of Christmas clues
This change simply copies existing code for the crossword and modifies the clue list to be Christmas theme, this means that we should avoid major refactoring and presumably retain the same amount of test coverage.
N/A

Add Christmas crossword

---

.circleci/config.yml

https://trello.com/c/zjaTxHxL/1824-kubernetes-deployments-failing
- Run a deploy to Development step on a preview branch
- Update Kubernetes Orb to `0.11.2` (latest)
- Update Helm Orb to `1.2.0` (latest)
N/A
N/A
A successful build and deploy in CircleCI should verify that the issue is fixed

Update deployment orbs to latest

---

server/auth/__tests__/middleware.spec.js
server/auth/middleware.js

https://trello.com/c/XSUYKalD/1773-server-side-url-redirect-security-warning
- Alter the `returnURL` parameter when logging in to be absolute
- The application should not redirect to the absolute URL but the homepage
Add validation for `returnUrl` parameter in the authentication middleware
- Redirect to the `returnUrl` if it is relative
- Redirect to the homepage if `returnUrl` is absolute or protocol-relative
N/A
N/A

Add validation for returnUrl in auth flow

---

.circleci/config.yml

https://trello.com/c/Stp7gjlf/1832-development-branches-arent-built-tested-in-circleci
✔ we can see no tests are run in the CircleCI dashboard
This PR flips the approval step for development environment deployments so the build happens first.
This _might_ be better if we split it into two different workflows, so we get a checkmark next to the tests rather than a "pending" because the approval step hasn't been used.
Check the CircleCI builds for this branch 
> Are there any steps required when …

Ensures tests are run for each non-main branch. Build before approval step

---

server/services/__tests__/hubContentService.spec.js
server/services/hubContent.js

https://trello.com/c/hwdHR1OQ/1873-content-pages-fail-to-load-when-the-term-api-returns-404
- Access `/content/3840` in Wayland
We add `.filter` to the resolved `Promise.all` when retrieving terms for content
N/A
This is not the ideal fix for this issue, ideally we should return these terms alongside the content. This is a quick fix for brevity.
N/A

Add code to filter when calls to the Term API return 404

---

README.md
cypress.json
cypress/e2e/homepage.spec.js

https://trello.com/c/2Rg3lbdM/1894-get-e2e-tests-running-locally
N/A
- Update Cypress base URL to allow for inferring prison from hostname
- Update home page tests to use absolute URLs for testing multiple sites
- Update documentation for running E2E tests
N/A
This PR is to get our existing E2E tests running in Cypress locally
N/A

Update Cypress configuration to run locally

---

helm_deploy/prisoner-content-hub-frontend/templates/deployment.yaml
server/__tests__/app.spec.js
server/app.js
server/auth/middleware.js
server/config.js

https://trello.com/c/7XkW9uMD/1931-how-do-we-test-sign-in-out-e2e
- Create mock auth middleware
- Add feature toggle `ENABLE_MOCK_AUTH`
So.....
- Clicking sign-in/out with mocking enabled will use a "test" user
Turns out mocking getting our AzureAD SSO set up with Cypress is difficult, especially with our current setup and how we intend to run these tests.
To ensure we're not blocked on this work, and until we have a better solution, there's this PR ☝️

Add feature toggle for mocking auth

---

server/repositories/__tests__/prisonApi.spec.js
server/repositories/prisonApi.js
server/routes/__tests__/money.spec.js
server/utils/__tests__/validators.spec.js
server/utils/validators.js

https://trello.com/c/dY96wSWn/1993-transactions-history-isnt-shown-in-production
- Log in with a production account
- Navigate to `/money/transactions`
- The transaction information will not be displayed
- Removed the length assertion for the Booking ID validator
- Booking ID's appear to be variable length, as opposed to fixed length as thought based on test accounts
Nope

Fix Booking ID validation for balances API call

---

server/repositories/__tests__/prisonApi.spec.js
server/repositories/prisonApi.js
server/services/__tests__/prisonerInformation.spec.js
server/services/prisonerInformation.js

https://trello.com/c/c6JWJSeX/1994-5xx-responses-from-frontend-dont-raise-sentry-alerts
To capture transaction exceptions in Sentry

Add sentry capture exception when getting transactions

---

server/routes/__tests__/formatters.spec.js
server/routes/formatters.js
server/utils/date.js

https://trello.com/c/yqqUn6b5/1996-add-additional-logic-to-split-out-batch-payments-for-transactions
- Split batch Payroll payments out, displaying the individual related transactions
Original code from Prisoner Staff Hub for reference:
`https://github.com/ministryofjustice/prisonstaffhub/blob/main/backend/controllers/prisonerProfile/prisonerFinances/prisonerSpends.js`

Add additional logic when formatting transactions to split batch payments

---

assets/sass/components/_personalised.scss
package-lock.json
package.json
server/routes/__tests__/money.spec.js
server/routes/money.js
server/utils/__tests__/date.spec.js
server/utils/date.js
server/views/components/personal-transactions/template.njk
server/views/pages/transactions.html

https://trello.com/c/HNOkkbXj/1933-i-would-like-to-select-the-date-range-transaction-history
- Add date selection for viewing transactions
There was an issue with using `Jest.useFakeTimers` with async functions, I've used `@sinonjs/fake-timers` for testing and added comments to explain the usage

Add date selection to the transactions page

---

server/auth/__tests__/middleware.spec.js
server/auth/middleware.js

Does this issue have a Trello card?
https://trello.com/c/c6JWJSeX
What changes are introduced by this PR that correspond to the above card?
Enable Sentry on middleware failure to authenticate
Is there any additional information that would help when reviewing this PR?
Eslint flagged no-underscore-dangle - commented code to ensure that the relevant variables are ignored

Add Sentry alerting on failure to authenticate

---

server/clients/__tests__/hubClient.spec.js
server/clients/__tests__/standardClient.spec.js
server/clients/hub.js
server/clients/standard.js

https://trello.com/c/c6JWJSeX/1994-5xx-responses-from-frontend-dont-raise-sentry-alerts
Enable Sentry on client failures

Add Sentry client alerting

---

server/app.js
server/routes/profile.js

No this is a minor fix
- Navigate to `/profile`
- Click "sign-in"
Expected behaviour: To be signed in and profile page to be visible
Current behaviour: Profile page  remains in a signed out state
- Moved setting the username back to the route

fix profile signin issue

---

server/repositories/__tests__/prisonApi.spec.js
server/repositories/prisonApi.js
server/routes/__tests__/money.spec.js
server/services/__tests__/prisonerInformation.spec.js
server/services/prisonerInformation.js

https://trello.com/c/O82U3mp8
View a transaction that occurred in an inactive prison such as Camp Hill
Altering the code that performs the prison name lookup to include inactive prisons. 
If I generate two lists of prisons from both the old and new endpoints, it produces the exact same output
```
curl -X GET  -v  "https://api-preprod.prison.service.justice.gov.uk/api/agencies/type/INST?activeOnly=true" -H "Authorization: Bearer $TOKEN" | jq '.[] | .description' > insts.txt
curl -X GET  -v …
```

Allow retrieval of the names of inactive prisons 

---

helm_deploy/prisoner-content-hub-frontend/values.yaml

https://trello.com/c/cJoa8Xdm/102-enable-moj-official-laptops-to-access-the-content-hub-frontend-npr-stream
This PR enables users on the MoJ OFFICIAL network to access the Prisoner Content Hub frontend.
- Validated supplied IP range on https://github.com/ministryofjustice/moj-ip-addresses/blob/main/moj-cidr-addresses.yml

Add MoJ Official network to IP allow list

---

server/routes/__tests__/formatters.spec.js
server/routes/formatters.js

https://trello.com/c/moVmbEYm
Navigate to the pending transactions page.
Pending transactions table amount column split to display "Money in" and "Money out" separately.
Probably.
n/a
no

jh-pending-transactions-split-out-the-amount

---

server/content/establishmentData.json

https://trello.com/c/4GFGbytk
Identified 404 errors in Sentry in relation to broken links on the popular topics for Wayland and Cookham Wood. Working links to exercise and facilities list restored with this PR

Bugfix popular topics links

---

Dockerfile

* https://trello.com/c/nXLfU3he
Whilst getting the build out for a fix to the release, we noticed that the docker image took a really long time to build.
This was due to it install cypress (testing library) as part of the production image.
This contains a copy of chromium which is really big.
On my laptop, setting the env flag to prevent the download reduces the build time by >40 seconds and the final image by >600m (over a 13/rd):
```
pch-w-cypress                          01          2fa3e69b3f16   8 minutes ago    1.61GB
pch-wo-cypress                         01          809705a0b2ae   24 minutes ago   993MB
```
No

Improving speed of docker image build and reducing image size

---

nodemon.json
package.json
server/app.js
server/clients/jsonApiClient.js
server/config.js
server/repositories/__tests__/cmsApi.spec.js
server/repositories/cmsApi.js
server/repositories/hubMenu.js
server/routes/__tests__/money.spec.js
server/routes/__tests__/topics.spec.js
server/routes/formatters.js
server/routes/topics.js
server/services/__tests__/topicsService.spec.js
server/services/hubMenu.js
server/services/index.js
server/services/topics.js
test/resources/primaryMenu.js

https://trello.com/c/cuCgbKtD
Put in place the start of a new json api client and extract out a cmsApi which will be the basis of new json api functionality.
I've then moved the existing json api call into it and ensured its covered by nock tests
As part of this I realised that the sorting on the topic page only checked the first character. This lead to strange results in certain cases: 
This has changed some of the error handling behaviour. 
The topic page is made out of landing pages and categories - previously if either call failed then it would still show the results of the other call. Not if one call fails it will show an error page. 
Could look at reinstating this if necessary, but going forward we will hopefully merge both calls into one by …

Extracting out a topic service and new json api client

---

server/repositories/search.js
server/routes/__tests__/health.spec.js
server/routes/health.js
server/services/__tests__/search.spec.js
server/services/search.js

https://trello.com/c/AHyLgirl
We were previously doing a term search on a text value.
This has [known limitations](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html#avoid-term-query-text-fields)
This would only work for single word prisons. The text value would be processed during index to split by individual word and lower case whereas the terms query would pass the exact phrase.
So when we searched for 'Cookham wood' it would fail to match either the tokens 'cookham' or 'wood'.
Luckily according to the index I could see that a separate  prison_name.keyword was also indexed which indexes the whole thing.
This change moves to using the formatted name and the keyword field as these currently always match.
We should see if drupal would allow us to …

bug/fix-search: Changing search type

---

.circleci/config.yml

We're ditching alerts and wanted the security vulnerabilities to go somewhere more apparent
https://trello.com/c/zYZByqzb

Move alert channel to dev channel for alerts

---

server/app.js
server/repositories/categoryFeaturedContent.js
server/utils/__tests__/nunjucksSetup.spec.js
server/utils/nunjucksSetup.js
server/views/pages/category.html
test/test-helpers.js

https://trello.com/c/S1EaJpo1
*Increase category page content limit to 10 items
*Add standalone nunjucks app setup
*Refactor category featured content logic

Increase category page content limit

---

.circleci/config.yml
helm_deploy/prisoner-content-hub-frontend/templates/NOTES.txt
helm_deploy/prisoner-content-hub-frontend/templates/ingress.yaml
helm_deploy/prisoner-content-hub-frontend/values.development.yaml
helm_deploy/prisoner-content-hub-frontend/values.production.yaml
helm_deploy/prisoner-content-hub-frontend/values.staging.yaml

https://trello.com/c/O5qXdz7V 
Creating individual dev deployments of the frontend app for each PR
Move to pushing through the circle CI PR number as a qualifier to distinguish between different helm releases.
This  qualifier is then fed into domain name construction
PR build 280 would listen to: 
* https://cookhamwood-prisoner-content-hub-development-280.apps.live-1.cloud-platform.service.justice.gov.uk
* https://berwyn-prisoner-content-hub-development-280.apps.live-1.cloud-platform.service.justice.gov.uk 
... etc 
These releases can be seen with: 
```
helm -n prisoner-content-hub-development list   
```
Further pushes to a remote branch with a PR on will lead to the app being upgraded. 
These environments will not currently be disposed of after merging - need to manually uninstall them …

Deploying adhoc development environments

---

.circleci/config.yml

In staging and prod there would be no qualifier so the helm release would be named `prisoner-content-hub-frontend-` which is invalid
This change only adds the `-` separator between release name and qualifier if qualifier is present

Fixing staging deployment

---

helm_deploy/prisoner-content-hub-frontend/templates/_envs.tpl
helm_deploy/prisoner-content-hub-frontend/values.development.yaml
helm_deploy/prisoner-content-hub-frontend/values.production.yaml
helm_deploy/prisoner-content-hub-frontend/values.staging.yaml

https://trello.com/c/gt21UBzk
We have done the work to create an environment per PR but unfortunately we cannot get production style auth working with these as it doesn't support dynamic URLs
We've agreed to use mock auth in dev instead and this change enables that. 
This will mean that we can actually  provision different users on different PRs or potentially have somekind of  user switcher.
Going forward we will only be able to test auth in staging
Need to ensure that mock auth is DISABLED in staging and prod during the release.

Enabling mock auth in dev

---

.circleci/config.yml

The source folder has moved in the docker image which is killing the veracode scheduled build

Fixing veracode job

---

server/auth/__tests__/middleware.spec.js
server/auth/middleware.js

https://trello.com/c/PSj4hCb0
When logged in with real auth, if you double click the logout button - it triggers a null pointer. 
This should fix the bug by not triggering logout if already logged out.
This bug only affects "real" auth, this branch is deployed to [dev](https://cookhamwood-prisoner-content-hub-development.apps.live-1.cloud-platform.service.justice.gov.uk/
) so can compare with [staging](https://cookhamwood-prisoner-content-hub-staging.apps.live-1.cloud-platform.service.justice.gov.uk/) which currently shows the bug.

Fix double click issue on logout

---

server/routes/__tests__/formatters.spec.js
server/routes/formatters.js

https://trello.com/c/YPw8oRCh
We have updated the code base to replace a related transactions balance function with the related Offender Transactions current balance from the prisonAPI  
Conducted further local testing by pulling transactions data from May. Pre/Post implementation data matched.

Update prisonAPI to include related transactions current balance

---

helm_deploy/prisoner-content-hub-frontend/values.yaml

https://trello.com/c/Qgdi5nC7/224-access-the-content-hub-frontend-from-globalprotect-vpn
This PR enables users on the GlobalProtect VPN to access the Prisoner Content Hub frontend, hopefully preventing the dreaded "are you using the right VPN" conversation.
IP range taken from https://github.com/ministryofjustice/moj-ip-addresses/blob/main/moj-cidr-addresses.yml and checked against local GlobalProtect settings.

Global protect vpn access

---

.circleci/config.yml

https://trello.com/c/VnJjg78y
When deployments to delete:
<kbd>
</kbd>
When no deployments to delete:
<kbd>
</kbd>
An extra step that runs as part of the daily scheduled job.
Deletes every PR release that no longer has an open PR.
I've tested this and it seems to work with a variety of situations.
Would be good to keep an eye on after merging to ensure that it acts as we expect it to behave.

Tidying up deployments that are no longer required

---

server/repositories/cmsQueries/__tests__/HomepageQuery.spec.js
server/repositories/cmsQueries/homepageQuery.js

https://trello.com/c/0yV9FDqz/239-use-new-resized-images-in-home-page
Should use resized images when present. Fallback to normal images if not present for whatever reason.
A good way to test this is viewing download page size in chrome in 
new vs old dev: 
https://cookhamwood-prisoner-content-hub-development-342.apps.live-1.cloud-platform.service.justice.gov.uk/
https://cookhamwood-prisoner-content-hub-development.apps.live-1.cloud-platform.service.justice.gov.uk/

Showing resized images on the homepage

---

server/repositories/hubContent.js

https://trello.com/c/ThoxbMHp
There's a huge amount of unnecessary error logging occurring around retrieving next content or related content for items that aren't series. 
This removes the logging so other errors will be more visible

Reducing error logging verbosity

---

server/app.js
server/repositories/__tests__/cmsApi.spec.js
server/repositories/apiError.js
server/repositories/cmsApi.js
server/repositories/hubContent.js

https://trello.com/c/AGF41AVL
Try and access content that doesn't exist: `/content/123456` or `/tag/123456`
Or content that is not available for a specific prison: `/content/5925` in berwyn
We now capture 404 errors when calling queries and convert them to 404 responses sent to the browser.
The router returns 403 responses when content exists but not at a specific prison - we are now handling these as well

Preventing missing content from triggering alerts

---

helm_deploy/prisoner-content-hub-frontend/templates/ingress.yaml
helm_deploy/prisoner-content-hub-frontend/values-development.yaml
helm_deploy/prisoner-content-hub-frontend/values-production.yaml
helm_deploy/prisoner-content-hub-frontend/values-staging.yaml

https://trello.com/c/SPrEP9m8/394-allow-a-user-to-access-the-hub-via-a-central-url
Adding an additional hostname for the single url
Also adding additional annotations required by cloud platform
Added it as a separate single item rather than trying to work with complicated system for generating hostnames from the host list as hopefully we can remove those at a (much) later date
Need to check ingress after deploying

Adding single url hostname

---

server/routes/__tests__/search.spec.js
server/routes/search.js
server/services/__tests__/search.spec.js
server/services/search.js
server/utils/index.js

No, part of the wider work around addressing tech debt to help with move to a single url
Starting to remove reliance on Establishment ID by moving the search over to use establishment in name
(I think establishment ID might be a better name that establishment Name to represent what we call "machine name" in drupal?, but think it would be good to remove all references to ID before moving over to use it )
Establishment Name should always be set in the session on the search page - either from the user or from the domain name

Moving to use establishment name rather than search name

---

helm_deploy/prisoner-content-hub-frontend/templates/_envs.tpl
server/config.js
server/routes/__tests__/analytics.spec.js
server/routes/analytics.js
server/views/components/template.njk
server/views/pages/externalLink.html
test/test-helpers.js
utils/index.js

Fix case when single url is used
https://trello.com/c/j68vCqlK
When we are using the single prison agnostic url we still want to be able to track per establishment usage via google analytics.
This builds up the url based on the session derived establishment id and the single host url. 
URL pattern differs between dev/staging and prod: `-` vs `.` separated.
This doesn't take that into account so will start to report different urls in dev and staging.
I don't think this matters but need to check

Send correct hostname to google analytics

---

server/middleware/__tests__/getEstablishmentFromUrl.spec.js
server/middleware/getEstablishmentFromUrl.js

Nope, small fix for when developing locally
When developing locally some developers use the following in /etc/hosts file:
`cookhamwood.prisoner-content-hub.local`
rather than
`cookhamwood.localhost`
and the service cannot determine which establishment the user is trying to access. This fixes that
existing behaviour for other environments should be maintained

Fix detecting establishment name when developing locally

---

.gitignore
.prettierignore
assets/javascript/showMore.js
assets/sass/components/_page-navigation.scss
nodemon.json
package.json
server/app.js
server/repositories/__tests__/cmsApi.spec.js
server/repositories/cmsApi.js
server/repositories/cmsQueries/__tests__/secondaryTagPageQuery.spec.js
server/repositories/cmsQueries/__tests__/seriesPageQuery.spec.js
server/repositories/cmsQueries/secondaryTagPageQuery.js
server/repositories/cmsQueries/seriesPageQuery.js
server/routes/__tests__/money.spec.js
server/routes/__tests__/tags.spec.js
server/routes/content.js
server/routes/tags.js
server/services/__tests__/cmsService.spec.js
server/services/cms.js
server/utils/__tests__/jsonApi.spec.js
server/utils/jsonApi.js
server/views/components/related-content/related-content.njk
server/views/components/related-content/template.njk
server/views/pages/tags.html

https://trello.com/c/w9ODRIv3
When showing the full results of a secondary tag or series, paginate them to allow more than 40 results to be shown (the current limit)

Add pagination to series secondary tags

---

server/utils/azureAppInsights.js

Logging lots of health requests, 230  in 5 minutes. 
This will remove them

Removing health endpoints from request logging

---

server/services/__tests__/search.spec.js
server/services/search.js
server/views/components/search/template.njk

https://trello.com/c/hYbFqugJ/
The following changes:
1.) limit frontend and typeahead search to only allow queries of up to 50 characters.
2.) Backend, never execute queries of over 50 characters, just return empty list instead
3.) Remove any character in a query which doesn't match one of the following characters a-zA-Z0-9';,\-()!"
We noticed that the search: `Using Unilink: Shopping / canteen` currently throws an error on the backend and shows no results on the frontend. If we strip out the `/` then it works and shows the correct result.
(This also works if we strip out both the / and the : which is why I'm not allowing : either) (edited)

Sanitising and limiting search input

---

server/repositories/cmsQueries/__tests__/categoryContentQuery.spec.js
server/repositories/cmsQueries/categoryContentQuery.js

https://trello.com/c/NKbqKG0z
What
At least one page is showing recently added or updated content at the end of the of the content, rather than at the beginning
Why
It is a bug that affects how content is being displayed, producing the opposite to the intended effect

Add category content sort query

---

server/repositories/cmsQueries/__tests__/searchQuery.spec.js
server/repositories/cmsQueries/searchQuery.js

This fixes the link to links
https://trello.com/c/EwL0hwwC
Rather than trying to guess the content that the url will be present in the hub, instead use the path as provided from drupal.
Think the search index needs rebuilding on dev, so might be easier to test elsewhere.

Add correct links for content

---

server/routes/__tests__/homepage.spec.js
server/routes/homepage.js
server/routes/index.js

https://trello.com/c/d1vzZdpJ/1150-prepare-to-release-new-homepage
n/a
- Rename current homepage route '/' to 'old-homepage'
- Rename 'new-homepage' route to '/'
- update supporting unit tests for the above homepage routes
no
- The new homepage is available on the default '/' route when visiting the hub.
- The current (old) homepage is available on the '/old-homepage' route when visiting the hub. 
no

1150 prepare to release the new homepage

---

server/views/components/mediaTemplate.njk

https://trello.com/c/i0UXWdOk/1443-unneeded-html-being-added-to-the-page-forcing-the-title-to-be-pushed-down-when-tag-data-is-not-present
na
- Added a condition to display the HTML related to displaying tag data only when the tag data (data.seriesId) is available. This prevents additional HTML being added to the view and pushing down the title. Whilst maintaining the ability to display the Tag when it is available.
**Prior to the change:**
**No tag available**
**After the change**
**No tag available**
**Tag available prior to and after the change**
> Is there any additional …

Add condition around display tag html

---

assets/sass/components/_urgent-banner.scss
assets/sass/style.scss
e2e/cypress/features/profile.feature.js
e2e/cypress/features/timetable.feature.js
e2e/cypress/mockApis/drupal.js
e2e/cypress/mockApis/drupalData/urgentBanners.json
e2e/cypress/support/step_definitions/common.js
server/__tests__/app.spec.js
server/middleware/urgentBannerMiddleware.js
server/repositories/cmsQueries/__tests__/urgentBannerQuery.spec.js
server/repositories/cmsQueries/urgentBannerQuery.js
server/routes/__tests__/profile.spec.js
server/routes/index.js
server/services/__tests__/cmsService.spec.js
server/services/cms.js
server/utils/__tests__/jsonApi.spec.js
server/utils/jsonApi.js
server/views/components/basicTemplate.njk
server/views/components/urgent-banner/macro.njk
server/views/components/urgent-banner/template.njk

https://trello.com/c/Isn6DtTl/997-allow-prisoners-to-see-urgent-notices-in-the-banner?filter=label:Front+End
n/a
- Added a new Urgent banner component and supporting styles
n/a
n/a

Add urgent banner component and styles

---

helm_deploy/prisoner-content-hub-frontend/templates/ingress.yaml
helm_deploy/prisoner-content-hub-frontend/values-development.yaml
helm_deploy/prisoner-content-hub-frontend/values-production.yaml
helm_deploy/prisoner-content-hub-frontend/values-staging.yaml

https://trello.com/c/uFrdiYUP/1712-switch-to-new-ingress-controllers
Switch to using new ingress controllers.  See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/Switch-ingress-to-v1-ingress-controller.htm
There was a previous PR https://github.com/ministryofjustice/prisoner-content-hub-frontend/pull/558 which did this but with 0 downtime.  However we couldn't get this to work (was unable to set the correct identifier for the dev environment).  So instead we are going with this option, which will incur some downtime.

Switch to new ingress controllers, with downtime.

---

assets/sass/_general.scss
server/repositories/cmsQueries/__tests__/audioPageQuery.spec.js
server/repositories/cmsQueries/__tests__/basicPageQuery.spec.js
server/repositories/cmsQueries/__tests__/categoryPageQuery.spec.js
server/repositories/cmsQueries/__tests__/seriesPageQuery.spec.js
server/repositories/cmsQueries/__tests__/topicPageQuery.spec.js
server/repositories/cmsQueries/__tests__/videoPageQuery.spec.js
server/utils/jsonApi.js

https://trello.com/c/0IXdWr6s/1793-increase-font-size-of-breadcrumb-to-19pt-remove-the-current-page
No.
- Updated SASS to increase breadcrumb font size
- Removed current page/content from the breadcrumb
- Fixed failing unit tests caused by the changes made
**Before:**
**After:**
No.
No.

Update breadcrumb font size and content

---

assets/images/icons/collection.svg
assets/sass/components/_tiles.scss
server/views/components/content-tile-featured/template.njk
server/views/components/content-tile-large/template.njk
server/views/components/content-tile-small/template.njk

https://trello.com/c/Vey2zhxu/1794-remove-collections-label-across-the-site
N.A
- Removal of the 'Collection' tag from the small tiles.
**Before:**
**After:**
No.
No.

Remove collection label from small tile component

---

helm_deploy/prisoner-content-hub-frontend/values-staging.yaml
server/routes/search.js
server/views/pages/search.html

https://trello.com/c/oKLpBn06/1811-determine-how-browser-caching-is-handled-on-prisoners-laptops
N.a
- Add Cache-Control header to no search results view.
no.
no
no

Add cache-control

---

assets/sass/components/_tiles.scss
server/views/components/content-tile-small/template.njk

https://trello.com/c/vJO681Xc/1816-create-series-tag-to-show-in-top-right-corner-of-tiles-for-drupal-series-across-site
N.A.
- Added a new 'SERIES' tag to the relevent tiles
- Updated / Added related CSS
No.
No.

Add series tag and styles

---

helm_deploy/prisoner-content-hub-frontend/values-production.yaml
server/routes/__tests__/money.spec.js

** FOR RELEASE ON MONDAY 5TH DECEMBER 2022 **
https://trello.com/c/McnktIOG/1821-release-disable-the-approved-visitors-list-feature
No.
- Feature flag toggled on.
- Fix date related unit tests.
No.
No.
No.

Enable approved visitors feature in production

---

server/routes/approvedVisitors.js
server/routes/profile.js
server/views/pages/approvedVisitors.html
server/views/pages/profile.html

https://trello.com/c/McnktIOG/1821-release-disable-the-approved-visitors-list-feature
No.
- Removing the establishment restriction to open up the approved visitors list to all prisons
- Updating the My Profile page tile to read ‘List of approved visitors - social’
- Updating the approved visitors list page title to read ‘List of approved visitors - social’
- Updating the approved visitors list page - no approved visitors screen to have the title above and the content to read ‘You do not have any approved social visitors….’
- Updating the approved visitors list page - error screen to have the title above and the content to …

Remove establishment restriction for approved visitors list

---

server/routes/search.js
server/views/pages/search.html

https://trello.com/c/iPmR3rcp/864-remove-fe-cache-header-in-search-used-during-testing-at-hmp-ranby
no
Revert changes made that enabled a test of in browser caching during an onsite test at HMP Ranby.
No.
No.
No.

Remove cache header

---

server/views/components/page-navigation/template.njk

https://trello.com/c/sFOjuaGG/1884-change-homepage-to-home-on-breadcrumb-trail-in-my-profile
no.
- Update homepage breadcrumb text to read 'home' instead of 'homepage'
No.
no.
no.

Update homepage breadcrumb text

---

assets/sass/components/_topbar.scss
server/views/components/top-bar/template.njk

https://trello.com/c/obYzbUtl/1879-add-hover-press-state-to-content-hub-hmp-prison-name-text-next-to-logo-in-top-left-corner
No.
- CSS styles added to the establishment link to provide GDS standard hover state and roll over state.
No.
No.

Update establishment link styles

---

README.md
server/content/breadcrumbs.json
server/routes/approvedVisitors.js
server/routes/createAnagramicaRouter.js
server/routes/games.js
server/routes/money.js
server/routes/profile.js
server/routes/timetable.js
server/utils/__tests__/breadcrumbs.spec.js
server/utils/breadcrumbs.js

https://trello.com/c/zQ7Pu7He/1824-add-breadcrumb-navigation-to-the-my-profile-and-games-sections-of-the-hub
No.
- Breadcrumbs added to the sections within My profile
- Breadcrumbs added to the Entertainment > games subpages 
No.
No.

Add custom breadcrumbs

---

package-lock.json
package.json

No card needed, minor package version fix.
na
Reverted jsona package back to 1.9.7 from 1.11.0
no
no
no

Revert jsona package version to 1.9.7

---

server/content/knownPages.json
server/repositories/__tests__/offenderRepository.spec.js
server/repositories/offender.js
server/routes/__tests__/profile.spec.js
server/routes/adjudications.js
server/routes/index.js
server/routes/profile.js
server/services/__tests__/offenderService.spec.js
server/services/offender/index.js
server/services/offender/responses/__tests__/adjudications.spec.js
server/services/offender/responses/adjudications.js
server/services/offender/responses/index.js
server/utils/__tests__/date.spec.js
server/utils/breadcrumbs.js
server/utils/enums.js
server/views/pages/adjudications.html
server/views/pages/profile.html

https://trello.com/c/jvrT7FkA/1997-adjudications-3-add-prison-api-call-and-show-hide-logic-to-my-profile
no
- Add API call to prison api - adjudications end point
- Add adjudications section to the My profile page with conditional display
- Add /adjudications route
- Add place holder adjudications list view - to be updated when designs finalised
- Add text link to read more about adjudications
- Add supporting unit tests
The feature is currently restricted to HMP Ranby.
> Are there any steps required when …

Add adjudications api call and data parsing

---

server/auth/middleware.js
server/clients/prisonApiClient.js
server/config.js
server/repositories/offender.js
server/routes/adjudications.js
server/utils/__tests__/pagination.js
server/utils/pagination.js
server/views/pages/adjudications.html

https://trello.com/c/yT7QImZG/2030-adjudications-4-adjudications-list-page
no.
- Add Page-Limit header to adjudications prison api call
- Add details text to list page
- Refactor pagination 
- Add unit tests to for createPagination
no
no

add links to adjudication detail page in list table

---

assets/sass/components/_update-items.scss

https://trello.com/c/4lVtHfZm/2062-implement-frontend-updates-based-on-accessibility-audit-findings-suggestions - point 21
no
- Update to CSS to fix hidden text when the browser text size is set to large / extra large
Before:
After:
no
no

Remove max-height property

---

assets/sass/components/_key-info-items.scss

https://trello.com/c/u8emcFnD/2094-accessibility-fix-29-key-info-tile-text-at-large-very-large
Change the browser appearance setting to use large / very large font sizes
- updated related CSS to ensure the key-info tile text is readable when then browser font-size setting is set to large or very large.
Before the updates:
After the updates:
- medium (recommended) font size
- large font size
- very large font size
No.
No.

Update key-info tile styles

---

server/views/pages/adjudications.html
server/views/pages/approvedVisitors.html

https://trello.com/c/jeQWP1mu/2096-font-mismatch-on-approved-visitors
N/A.
- Added missing style class to html element in /approved-visitors and /adjudications views.
**After update:**
No.
No.

Add missing font style class

---

server/views/components/content-tile-small/template.njk

https://trello.com/c/RlBYeHtI/2102-reposition-the-new-tag
N/A
- Reposition the 'NEW' tag on the small content tile
**Before the change:**
**After the change:** 
No.
No.

Reposition NEW tag

---

assets/images/icons/watch.svg
assets/sass/components/_tiles.scss

https://trello.com/c/kckvndb0/2103-replace-watch-icon-with-an-svg-to-bring-inline-with-read-and-listen-tiles
n/a
- Add .svg watch icon
- Updated CSS to use the .svg in place of the text
No.
No.
No.

Accessibility update: Replace watch icon with SVG

---

server/views/components/card/macro.njk
server/views/components/content-tile-featured/template.njk
server/views/components/content-tile-large/template.njk
server/views/components/content-tile-small/template.njk
server/views/components/episode-content-item/template.njk
server/views/components/update-items/template.njk

https://trello.com/c/D9Rs1jcv/870-introduce-image-lazy-loading
Adding `loading="lazy"` to relevant images. Not sure if these are the full group but seem to be.
No.
No
No

Add lazy loading attribute to images

---

server/views/components/key-info-items/template.njk

https://trello.com/c/D9Rs1jcv/870-introduce-image-lazy-loading
Added `loading="lazy"` to key info tiles.
No
No
No

Add lazy loading to key info tiles

---

server/views/pages/adjudication.html

https://trello.com/c/5eSk2ts7/2114-update-remove-reported-by-values-from-the-adjudication-detail-view
N/A
- Removed 'Reported by' data from the adjudication detail view
**Prior to the update:**
**After the update:**
No.
No.

Remove reported by data from view

---

server/app.js

No
NA
This will reduce overall Sentry Transaction usage by approximately by 75%, with no impact on Errors being sent to Sentry.
This is done by ignoring the **POST /analytics/page'** and  **POST /analytics/event'**. These endpoints are a technical workaround to send data to Google Analytics, so presumably, there's little value in the Transaction being sent to Sentry, and **POST /analytics/page'** is sent for every page load within the system, so using a disproportionate amount of transactions.
This PR also reduces the total sampling rate from 25% to 5%.
With both proposed changes, we're estimated to save 5million …

Refactor `Sentry` configuration to reduce transaction consumption

---

server/views/components/basicTemplate.njk

https://trello.com/c/b1cIq1Tk/2150-add-ga4-code-block-into-basictemplatenjk-for-testing-establishment-access-to-ga4-urls
N/A
- Added GA4 code block to the basicTemplate.njk file that is used throughout the frontend application for the purpose of testing allow listing of the GA4 URLs from the establishments, by monitoring the GA4 production property realtime dashboard for activity post deployment to production.
No.
No.
No.

Add GA4 code block to basicTemplate.njk

---

server/views/components/basicTemplate.njk

https://trello.com/c/4YdTQGY1/2160-spike-investigate-low-pageview-hits-in-ga4
N/A
- Reimplements the Universal Analytics code block into the basic template in order to compare UA/GA4 traffic in production.
No.
No.
No.

Add UA code block

---

e2e/cypress/features/health.feature.js
server/routes/__tests__/health.spec.js
server/routes/health.js

No
Current `/health/readiness` endpoint returns `OK`, it needs to return `UP`

Change readiness to UP from OK

---

server/auth/middleware.js

Dump out bookingId/agencyId from NOMIS to check

---

server/utils/__tests__/azureInsights.spec.js
server/utils/azureAppInsights.js

Sentry was registering extra events against app insights.

Disable capturing of inproc dependencies in app insights

---

e2e/cypress/features/health.feature.js
server/routes/__tests__/health.spec.js
server/routes/health.js

No.
This updates the output of the `/health` endpoint to match the standard used across frontend apps to help with status checking in the developer portal for the SRE and service teams.

Update health endpoint to reflect other apps

---

.circleci/config.yml
helm_deploy/prisoner-content-hub-frontend/templates/NOTES.txt
helm_deploy/prisoner-content-hub-frontend/templates/_envs.tpl
helm_deploy/prisoner-content-hub-frontend/templates/ingress.yaml
helm_deploy/prisoner-content-hub-frontend/values-development.yaml

Yes
It removes the multiple deployments in dev so there is a single deployment for a PR/branch as per other environments and products.
No.
No
No.

LNP-1112: Move to single deployment

---

assets/sass/components/_topbar.scss
server/views/components/top-bar/template.njk

https://dsdmoj.atlassian.net/browse/LNP-1122
Open the content hub front end and tab to focus on the Content Hub title or the language switcher (only The Studio has the language switcher configured at present). These display in white text rather than black when focused:
Removes the explicit setting of topbar links to white in CSS - instead applies the correct existing styles to those links.
Yes, have some:
You can read https://design-system.service.gov.uk/get-started/focus-states/
> Are there any steps …

LNP-1122: 💄  fix focus styles in header.

---

server/config.js

https://dsdmoj.atlassian.net/browse/LNP-1091
N/A
Changes configuration so that Profile is not available for all remaining prisons except Cardiff, Bullingdon (and etwow, which isn't real).
No
No
This should be preceded by https://dsdmoj.atlassian.net/browse/LNP-1092, so that there is no longer a broken link to the profile in Drupal.

LNP-1091: 🔧  remove profile from remaining sites except Cardiff and Bullingdon

---

server/config.js

https://dsdmoj.atlassian.net/browse/LNP-1143
N/A
Adjusts config to remove Profile from Bullingdon and Cardiff in advance of that capability being removed from the application.
No
No
This should be done after https://dsdmoj.atlassian.net/browse/LNP-1132 has been completed.

LNP-1143: 🔧  remove profile from Bullingdon and Cardiff.

---

server/routes/homepage.js

No
Check logs for `06:41:56.238Z  INFO Prisoner Content Hub Frontend: OffenderService (getCurrentEvents) - User: ???????`

Stop fetching events when timetable disabled

---

server/repositories/cmsQueries/__tests__/recentlyAddedContentQuery.spec.js
server/repositories/cmsQueries/recentlyAddedContentQuery.js
server/routes/recentlyAdded.js
server/routes/topics.js
server/services/__tests__/cmsService.spec.js
server/services/cms.js

https://dsdmoj.atlassian.net/browse/LNP-1167
Visit the topics page. It will error.
Visit the recently added page for Cardiff. Switch language to Welsh. The page will remain stubbornly English.
Fix language determination for topics and recently added, making it uniform with other routes.
Pass language parameters where appropriate for recently added functionality.
No
No
No

LNP-1167: fix topics page and make recently added page translatable.

---

server/routes/recentlyAdded.js

[LNP-1167](https://dsdmoj.atlassian.net/browse/LNP-1167)
Navigate to the Recently Added Page.
Scroll to the bottom of the content and click the _Show more_ button.
No more content shall be shown.
Note this is not an issue on production - this is a follow up to the previous LNP-1167 PR which has not yet been deployed. Thus this can only be observed on staging.
Adds a language parameter when getting content in response to the AJAX call for the _Show more_ button on this page.
No.
No
> Are there any steps …

LNP-1167: 🐛  fix ajax call for Show More button on Recently Added page.

---

assets/javascript/games/solitaire/main.js

LNP-1222 - Github scan warning for DOM text reinterpreted as HTML
Updated code to avoid using HTML attributes directly. Fixes scan warning
It took a couple of attempts to find a solution the code scan was happy with but the latest commit is showing the issue as fixed

LNP-1222: Updated solitaire - DOM text reinterpreted as HTML

---

assets/javascript/games/sudoku/sudokuJS.js

LNP-1221: Unsafe HTML constructed from library input
Using `.textContent` to ensure rendered HTML is safe as per guidance here:
https://cheatsheetseries.owasp.org/cheatsheets/DOM_based_XSS_Prevention_Cheat_Sheet.html#rule-7-fixing-dom-cross-site-scripting-vulnerabilities
N/A

LNP-1221: Sudoku - Unsafe HTML constructed from library input

---

server/app.js

LNP-1219: Helmet config missing CSP config - highlighted by Github scan
Added a loose content security policy to give some basic protection and fix the issue github code scanning is reporting.
We ideally would want to have a more strict CSP and not allow `unsafe-inline` scripts. However this would require more work such as adding randomly generated nonces to inline scripts and styles.
Question is - do we want to do this now and expand the scope beyond just fixing the scan warning, or do we want to add a new item to the backlog for enhancing the CSP beyond what's covered here?

LNP-1219: Add CSP rules

---

package-lock.json
package.json
server/routes/__tests__/feedback.spec.js
server/routes/feedback.js

JIRA ticket: LNP-1217
The ID in the `/feedback/:feedbackId` route is now validated, ensuring it is a valid UUID. This stops anything other than UUIDs from being logged/stored.
N/A

LNP-1217: Add validation to feedback id
