- server/app.js
- Pass in default option to config
> Fix deprecated warning in tests in body-parser

- .mocharc.yml
- .prettierignore
- test/mocha.opts
> Convert mocharc.opts to .mocharc.yml

- helm_deploy/prisoner-content-hub-frontend/templates/_helpers.tpl
- helm_deploy/prisoner-content-hub-frontend/values.yaml
- Update to use release name
- Add service tier label
> Update Helm configuration

- helm_deploy/prisoner-content-hub-frontend/readme.md
- helm_deploy/prisoner-content-hub-frontend/secrets.example.yaml
- helm_deploy/prisoner-content-hub-frontend/templates/_helpers.tpl
- helm_deploy/prisoner-content-hub-frontend/templates/deployment.yaml
- helm_deploy/prisoner-content-hub-frontend/values.local.yaml
- helm_deploy/prisoner-content-hub-frontend/values.non-prod.yaml
- helm_deploy/prisoner-content-hub-frontend/values.prod.yaml
- helm_deploy/prisoner-content-hub-frontend/values.yaml
- Split configuration by usage
- Update helpers to template ES host
- Add readme
> Update Helm Chart

- helm_deploy/prisoner-content-hub-frontend/templates/ingress.yaml
- helm_deploy/prisoner-content-hub-frontend/values.yaml
- Add annotations as suggested here https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/modsecurity.html\#ingress-annotations
> Add CP security to Ingress

- .circleci/config.yml
- Add command for Helm releases
- Add job for production release
- Update workflow for main branch
- Update workspace name
> Update CircleCI configuration for Helm releases

- helm_deploy/prisoner-content-hub-frontend/values.yaml
- Add VPN CIDR to whitelist
- Add no robots headers to responses
> Configure Nginx ingress

- helm_deploy/prisoner-content-hub-frontend/templates/ingress.yaml
And I sort-of-promise I'll buy a round of beers if this isn't the last PR for today
> Copy typo-fixes across from backend

- .circleci/config.yml
- helm_deploy/prisoner-content-hub-frontend/values.establishment-berwyn.yaml
- helm_deploy/prisoner-content-hub-frontend/values.establishment-wayland.yaml
This PR adds Wayland and Berwyn frontend services for testing
> Add wayland and berwyn sites to cloud platform

- .circleci/config.yml
- helm_deploy/prisoner-content-hub-frontend/readme.md
- helm_deploy/prisoner-content-hub-frontend/templates/deployment.yaml
- helm_deploy/prisoner-content-hub-frontend/values.yaml
- Update Helm to use livestream URL from configmap
- Update CI/CD
- Udpate Helm readme
> Update Helm to include configuration for NPR Live Stream

- .circleci/config.yml
- Update jobs to match backend
- Remove Azure deploys
> Make CircleCI same as backend CI

- .circleci/config.yml
- Removed deploy step to Development for the main branch
- Re-implemented unit and integration tests for all branches
> Update Circle pipeline

- helm_deploy/prisoner-content-hub-frontend/values.development.yaml
- helm_deploy/prisoner-content-hub-frontend/values.local.yaml
- Set Dev to Always, this will support using the preview tag
- Set Local to Never, allowing the use of local Docker builds
> Update Kubernetes image pull policy

- helm_deploy/prisoner-content-hub-frontend/values.establishment-berwyn.yaml
- helm_deploy/prisoner-content-hub-frontend/values.establishment-cookhamwood.yaml
- helm_deploy/prisoner-content-hub-frontend/values.establishment-wayland.yaml
- Add GA ids for each site in values yaml files
> Sites have unique GA ids

- Dockerfile
Error was suppressed but output in build.
- Add python install
- Add make install
> Add python to the Dockerfile to prevent an error

- package-lock.json
- package.json
- server/config.js
- server/repositories/offender.js
- server/routes/money.js
- server/services/offender.js
- server/utils/index.js
- server/views/components/personal-balance/template.njk
- test/services/offenderService.spec.js
- Remove utility functions
- Remove calls to BT endpoint
- Remove display on front-end
- Remove tests
- Remove config
> Remove BT PIN code

- package-lock.json
- https://npmjs.com/advisories/1213
> Fix vuln in dot-prop package

- helm_deploy/prisoner-content-hub-frontend/templates/deployment.yaml
- helm_deploy/prisoner-content-hub-frontend/values.development.yaml
- helm_deploy/prisoner-content-hub-frontend/values.establishment-berwyn.yaml
- helm_deploy/prisoner-content-hub-frontend/values.establishment-cookhamwood.yaml
- helm_deploy/prisoner-content-hub-frontend/values.establishment-wayland.yaml
- helm_deploy/prisoner-content-hub-frontend/values.staging.yaml
- helm_deploy/prisoner-content-hub-frontend/values.yaml
- server/config.js
- server/routes/index.js
- server/routes/npr.js
- server/views/pages/home.html
- server/views/pages/npr.html
- test/routes/index.spec.js
- FEATURE_NEW_DESIGNS becomes ENABLE_PERSONAL_INFORMATION
- newDesigns in the config object becomes personalInformation
> Rename new designs feature flag

- server/app.js
- server/middleware/configureEstablishment.js
- test/middleware/configureEstablishment.js
- Middleware to put prison info into session etc was removed
> Fix problem with prison data

- server/repositories/analytics.js
- server/routes/analytics.js
- server/services/analytics.js
- server/views/components/template.njk
- test/repositories/analytics.spec.js
- Custom dimension for secondary tags
- Custom dimension for categories
> Add categories and secondary tags to GA

- server/services/hubContent.js
- server/views/components/template.njk
- test/services/hubContentService.spec.js
- Parse existing secondary tags into a string
- Add categories in the same way as secondary tags
- Amend data sent to GA
- Amend test
> Return textual names for secondary tags and categories

- server/index.js
- Improve code consistancy
- Re-use single client instance for repositories
> Refactor service and repository bootstrap

- server/routes/npr.js
- server/views/pages/npr.html
- Make formatting the same as audio
- Remove useless features i.e. suggested content, series as never used
- Use default thumbnail to make layout look better
> Tidy up NPR page template

- assets/sass/components/_personalised.scss
- server/services/offender/responses/balances.js
- server/views/components/personal-balance-single/template.njk
- server/views/components/personal-balance/macro.njk
- server/views/components/personal-balance/template.njk
- server/views/pages/category.html
- test/services/offender/responses/balances.spec.js
- Add handling for a logged out state
- Move balances on to single line
- Update SASS
> Update Balances design

- assets/sass/components/_personalised.scss
- assets/sass/components/_timetable-one-day.scss
- server/services/offender/index.js
- server/views/components/personal-balance/template.njk
- server/views/components/personal-iep/template.njk
- server/views/components/personal-schedule-day-block/template.njk
- server/views/components/personal-schedule-one-day/template.njk
- Update balances placeholder
- Update timetable placeholder
- Fix timetable error content
- Add placeholder to IEP error state
- Update timetable error message
> Fix design for IEP, Balances, Timetable

- server/services/offender/index.js
- server/views/components/personal-schedule-today/template.njk
As per card https://trello.com/c/ablOKZx1
- Change appointments to events
- Remove event filter
> Change home page todays events

- server/app.js
- server/config.js
- server/utils/logger.js
- server/views/pages/error.html
- test/app.spec.js
- utils/index.js
- Remove unused environment flags
- Add feature toggle for stack traces
- Refactor error page to have home and back links
> Refactor error page

- server/views/pages/error.html
- Remove font sizing from error message to be consistant with 404 page
> Remove font sizing from error message

- server/app.js
- server/views/components/content-tile-large/template.njk
- server/views/components/content-tile-small/template.njk
- server/views/pages/category.html
- server/views/pages/home.html
- test/routes/content.spec.js
- test/routes/games.spec.js
- test/routes/gettingAJob.spec.js
- test/routes/index.spec.js
- test/routes/search.spec.js
- test/routes/tags.spec.js
- test/routes/topics.spec.js
- analyticsService not used most placfes
- logger not used in tests anymore
- IE specific code not required
> Remove more redundant code

- server/repositories/hubContent.js
- test/repositories/hubContent.spec.js
- menuFor is not used
- featuredContentFor is not used
- Remove tests
> Remove unused functions

- server/config.js
- server/repositories/categoryFeaturedContent.js
- Move /featured into config for endpoint
- Renamed endpoint config name to make sense
> Rename API endpoint

- server/middleware/configureEstablishment.js
- server/views/components/template.njk
- server/views/components/top-bar/template.njk
- server/views/pages/404.html
- server/views/pages/audio.html
- server/views/pages/authError.html
- server/views/pages/category.html
- server/views/pages/flat-content.html
- server/views/pages/games/chess.html
- server/views/pages/games/crossword.html
- server/views/pages/games/invadersfromspace.html
- server/views/pages/games/mimstris.html
- server/views/pages/games/neontroids.html
- server/views/pages/games/smashout.html
- server/views/pages/games/solitaire.html
- server/views/pages/games/sudoku.html
- server/views/pages/getting-a-job-content.html
- server/views/pages/getting-a-job.html
- server/views/pages/home.html
- server/views/pages/npr.html
- server/views/pages/search.html
- server/views/pages/signin.html
- server/views/pages/tags.html
- server/views/pages/timetable.html
- server/views/pages/topics.html
- server/views/pages/video.html
- test/middleware/configureEstablishment.js
- Causes confusion as establishmentName is also used as just the name
- Mostly it is actually the display name containing the prefix
> Rename establishmentName to establishmentDisplayName

- assets/javascript/all.js
- Add event to showHiddenBlock to cover both instances
> Add GA events to show buttons

- server/config.js
- server/repositories/hubFeaturedContent.js
- v2 api featured content move
> Move all endpoints to config

- .env-template
- README.md
- helm_deploy/prisoner-content-hub-frontend/templates/deployment.yaml
- helm_deploy/prisoner-content-hub-frontend/values.establishment-berwyn.yaml
- helm_deploy/prisoner-content-hub-frontend/values.establishment-cookhamwood.yaml
- helm_deploy/prisoner-content-hub-frontend/values.establishment-wayland.yaml
- helm_deploy/prisoner-content-hub-frontend/values.yaml
- server/app.js
- server/clients/hub.js
- server/config.js
- server/middleware/configureEstablishment.js
- server/repositories/hubContent.js
- server/routes/content.js
- server/routes/feedback.js
- server/routes/incentives.js
- server/routes/index.js
- server/routes/money.js
- server/routes/search.js
- server/routes/tags.js
- server/routes/topics.js
- server/routes/visits.js
- server/services/hubContent.js
- test/clients/hubClient.spec.js
- test/middleware/configureEstablishment.js
- test/routes/index.spec.js
- Switches most config in app.js
- Need to get switched config into server/clients/hub.js
> Base establishment on hostname

- server/views/components/template.njk
- Real code required for checking from a webpage
- Only page tracks and using dev account so as not to ruin current analytics
> Add real front-end GA code for testing

- server/views/pages/home.html
- server/views/pages/tags.html
- Homepage should be Home
- Tags should be the title amnd not establishment name
> Fix page titles

- helm_deploy/prisoner-content-hub-frontend/values.production.yaml
- Per site is now in config.js
> Enable overall personalisation in prod

- server/app.js
- server/auth/middleware.js
- server/clients/prisonApiClient.js
- server/clients/standard.js
- server/index.js
- server/middleware/configureEstablishment.js
- server/repositories/hubMenu.js
- server/repositories/offender.js
- server/repositories/search.js
- server/routes/analytics.js
- server/routes/content.js
- server/routes/feedback.js
- server/routes/incentives.js
- server/routes/index.js
- server/routes/money.js
- server/routes/npr.js
- server/routes/search.js
- server/routes/tags.js
- server/routes/topics.js
- server/routes/visits.js
- server/utils/adapters.js
- server/utils/index.js
- Remove Ramda's path and pathOr calls
- Replace with optional chaining in native JS
> Move to optional chaining

- assets/javascript/all.js
- assets/javascript/balances.js
- assets/sass/components/_personalised.scss
- server/views/components/personal-balance-single/template.njk
- server/views/components/personal-balance/template.njk
> Refactor design of balance component

- .github/pull_request_template.md
https://trello.com/c/9RsqlYZV/1766-add-pr-template
`Feature` and `Issue` templates have been added to enforce consistency when raising Pull Requests
N/A
N/A
> Add PR templates for issues and features

- server/views/components/personal-transactions/template.njk
Nope, it's a minor content fix
Fix content on transactions help link
> Fix typo on transactions page

- server/repositories/__tests__/prisonApi.spec.js
- server/repositories/prisonApi.js
https://trello.com/c/3X7tu4po/1961-damage-obligations
- Update the Prison API repository to include Damage Obligations
> Add Damage Obligations to Prison API repository

- server/services/__tests__/prisonerInformation.spec.js
- server/services/prisonerInformation.js
https://trello.com/c/3X7tu4po/1961-damage-obligations
- Update the Prisoner Information service to include Damage Obligations
> Add damage obligations to prisoner information service

- .circleci/config.yml
- helm_deploy/prisoner-content-hub-frontend/secrets.example.yaml
- helm_deploy/prisoner-content-hub-frontend/templates/deployment.yaml
- server/__tests__/app.spec.js
- server/app.js
https://trello.com/c/c6JWJSeX
- Enable Sentry request and error handling middleware 
- Sentry error handler was misconfigured - commented code to prevent misconfiguration in the future
- Because the Sentry handler was not present before, we are likely to see an increase in alerting on Sentry
> Enable Sentry request and error handling middleware

- server/views/components/personal-balance/template.njk
https://trello.com/c/fzJVBA9c/2018-fix-typo-when-logged-out-on-balances
- Fix typo on balances page
> Fix typo on balances page

- server/views/pages/timetable.html
https://trello.com/c/DuPwJr2D/2016-i-would-like-to-leave-feedback-when-viewing-my-timetable
- Add feedback to the timetable page
> Add feedback mechanism to the timetable page

- server/app.js
- server/routes/profile.js
- server/views/pages/profile.html
https://trello.com/c/VOMjYuaR
PR to implement the profile page boilerplate and enable gradual implementation and testing of the profile page  
> Add profile page boilerplate

- assets/sass/components/_personalised.scss
- server/views/components/personal-transactions/template.njk
https://trello.com/c/mGyErhYA
- Update to the date selection description on the transaction page to match the new designs (see Trello card)
> Update date selection on transactions page to match new design

- server/views/components/personal-transactions-private/template.njk
Nope, this is a minor content change
- Update description for pending transactions
> Update content for pending transactions

- .circleci/config.yml
- helm_deploy/prisoner-content-hub-frontend/templates/deployment.yaml
- server/app.js
- server/views/components/personal-balance-single/template.njk
- server/views/components/personal-damage-obligations/template.njk
- server/views/components/personal-important-dates/template.njk
- server/views/components/personal-incentives/template.njk
- server/views/components/personal-keyworker/template.njk
- server/views/components/personal-schedule-day-block/template.njk
- server/views/components/personal-schedule-today/template.njk
- server/views/components/personal-transactions-private/template.njk
- server/views/components/personal-transactions/template.njk
- server/views/components/personal-visits/template.njk
- server/views/components/template.njk
- server/views/components/user-details/template.njk
https://trello.com/c/YMeUfcLL
- Add HotJar to the main template
- Suppress personal information
- Update Helm configuration to allow HotJar ID to be configurable
- Update Circle configuration to allow HotJar ID to be configurable
- This should be tested extensively in Development to ensure personal information is suppressed
- Circle will need `HOTJAR_ID` adding
> Add initial HotJar integration

- .env-template
- README.md
- helm_deploy/prisoner-content-hub-frontend/readme.md
- server/__tests__/app.spec.js
- server/app.js
No, this just covers a few documentation fixes and a logging fix
* Removing unused env vars and incorrect endpoint url from env template
* Updating doc'd node version
* Only log missing hot jar at startup rather than every request
No
No 
> A few small changes:

- assets/javascript/card.js
- assets/sass/_general.scss
- assets/sass/components/_card.scss
- assets/sass/components/_personalised.scss
- server/routes/__tests__/profile.spec.js
- server/routes/profile.js
- server/services/offender/responses/__tests__/importantDates.spec.js
- server/services/offender/responses/__tests__/incentives.spec.js
- server/services/offender/responses/__tests__/nextVisit.spec.js
- server/services/offender/responses/incentives.js
- server/utils/enums.js
- server/views/components/card/macro.njk
- server/views/pages/profile.html
https://trello.com/c/fFl60oks
Add the visit's information to the profile page
Date format updated for personalization inline with GDS requirements
> Add visits to profile page

- server/routes/__tests__/profile.spec.js
- server/routes/profile.js
- server/services/offender/responses/__tests__/nextVisit.spec.js
- server/services/offender/responses/nextVisit.js
- server/views/components/personal-visits/template.njk
- server/views/pages/profile.html
https://trello.com/c/pqBnwdfS
I used the prisoner with number: `G2320VD` who has no visits planned.
> Handle when no next visit is planned

- server/__tests__/app.spec.js
- server/repositories/__tests__/offenderRepository.spec.js
- server/repositories/offender.js
- server/routes/__tests__/index.spec.js
- server/routes/index.js
- server/services/__tests__/offenderService.spec.js
- server/services/offender/index.js
- server/views/components/personal-schedule-today/template.njk
- server/views/components/user-details/template.njk
- server/views/pages/home.html
Does this issue have a Trello card?
https://trello.com/c/fwj5sXxY
*Add homepage events tests
*Update homepage signin/out tests
> Fix homepage events

- server/content/establishmentData.json
- server/routes/__tests__/index.spec.js
- server/utils/index.js
- server/views/pages/profile.html
https://trello.com/c/vcaJxjXw
View profile page and read private savings card
> Fixing typo on private savings card

- helm_deploy/prisoner-content-hub-frontend/values.yaml
https://trello.com/c/pqGiEBkJ/122-add-jon-marler-to-frontend-ip-allow-list
Jon needs short-term access to the Prisoner Content Hub to test URL allow listing in the Digital Prison Network. Once we've got everything up and running we can remove this rule.
Should we create a new Trello card to track the removal?
> Add Jon Marler (Jon.Marler1@justice.gov.uk) to IP allow list.

- README.md
- helm_deploy/prisoner-content-hub-frontend/values.yaml
- server/content/establishmentData.json
https://trello.com/c/DrPUH3Ej
To add Lindholme domain 
Deploy to production once PR request to cloud platform has been actioned 
https://github.com/ministryofjustice/cloud-platform-environments/pull/4802
> Add Lindholme

- .env-test
- package.json
- server/config.js
- server/repositories/offender.js
- server/repositories/prisonApi.js
- server/routes/__tests__/money.spec.js
- server/services/index.js
Remove need to set up project specific IDE settings to run tests and simplify consuming of env vars.  
Need to check retrieval of personalisation in dev - as some refactoring of urls
> Removing jest config

- .circleci/config.yml
> Fix veracode policy scan job

- Makefile
https://trello.com/c/FlQEHiLV
Yes. When trying to deploy to staging, it doesn't work :-)
Tweaks to the makefile production tag name.
No.
See the previous attempts at getting this to work 😬 
> 🐛 👷 makefile-build-tag-fix

- server/content/establishmentData.json
Adding accidentally removed Lindholme
Adding it back in
Need to check can access Lindholme and topics page
> Adding Lindholme back in

- helm_deploy/prisoner-content-hub-frontend/values.yaml
https://trello.com/c/sAAoh9oc/176-jon-marler-ip-update
- Update's Jon Marler (Digital Prison Network) as his IP address has changed again.
> Update Jon Marler IP

- audit-ci.json
> DT-2208: 🐛 Fix audit so that actually runs

- helm_deploy/prisoner-content-hub-frontend/templates/_envs.tpl
This wasn't working as reading value from wrong place, now reading it from the correct place.
tested this using:
```
helm template release ./helm_deploy/prisoner-content-hub-frontend/  
--values ./helm_deploy/prisoner-content-hub-frontend/values.production.yaml 
--values ./helm_deploy/prisoner-content-hub-frontend/secrets.example.yaml 
```
> Fixing mock auth

- .circleci/config.yml
Only showing the top 10 lines of the generated notes and only show branch name when its a PR
> Feature/reduce  length of release notes

- .circleci/config.yml
- server/views/pages/profile.html
https://trello.com/c/xGJi2G5t
Adding IEP level to Incentive label as many prisoners know Incentives as IEP
Also moving clean up job to happen as part of main build - it currently doesn't run as part of a schedule as it requires a context
> Adding IEP to label

- .circleci/config.yml
https://trello.com/c/GjuuhBYp
Moving to use new ssh key
Will need to roll out to prod to check to see if tag is created correctly
> Removing Ryan's ssh key and moving to deploy key

- server/content/establishmentData.json
https://trello.com/c/1B7SuR4R
To change the landing page called 'Guide to CW' to  'What goes on in Cookham
> Amend CW homepage link

- audit-ci.json
https://trello.com/c/uY9lYuvK
ignoring false positive audit issues
> Ignoring irrelevant issues

- server/routes/__tests__/tags.spec.js
- server/routes/tags.js
- server/services/hubTags.js
https://trello.com/c/UUtVQdiq/266-remove-potentially-unused-related-content-route
N/A
code removed
no
n/a
n/a
> remove-potentially-unused-related-content-route

- server/config.js
- server/repositories/cmsApi.js
- server/repositories/cmsQueries/AudioPageQuery.js
- server/repositories/cmsQueries/__tests__/audioQuery.spec.js
- server/routes/__tests__/content.spec.js
- server/routes/content.js
- server/services/__tests__/cmsService.spec.js
- server/services/__tests__/hubContentService.spec.js
- server/services/cms.js
- server/services/hubContent.js
- server/services/index.js
- server/views/pages/audio.html
- test/resources/radioShowServiceResponse.json
https://trello.com/c/m9nrhgHf
To introduce JSON API to Audio pages
> Feature/moving to use JSON API for audio page

- audit-ci.json
- package-lock.json
- package.json
- server/app.js
- server/routes/index.js
- test/test-helpers.js
…inks
https://trello.com/c/rJHDuj88/
So we can distinguish between users guessing content urls vs broken navigation
Also updating/fixing audit
Adding request url to uncaught exception message
Extracting routes into own file
Removing unnecessary dependency
> Adding internal referral headers

- server/repositories/cmsQueries/__tests__/audioPageQuery.spec.js
- server/repositories/cmsQueries/__tests__/videoPageQuery.spec.js
- server/repositories/cmsQueries/audioPageQuery.js
- server/repositories/cmsQueries/videoPageQuery.js
https://trello.com/c/Ip8ArIsD
Use resize images for thumbnails on video and audio pages
> Using resized images for thumbnails on video and audio pages

- server/repositories/cmsQueries/__tests__/audioPageQuery.spec.js
- server/repositories/cmsQueries/__tests__/nextEpisodeQuery.spec.js
- server/repositories/cmsQueries/__tests__/videoPageQuery.spec.js
- server/repositories/cmsQueries/audioPageQuery.js
- server/repositories/cmsQueries/nextEpisodeQuery.js
- server/repositories/cmsQueries/videoPageQuery.js
- server/services/__tests__/cmsService.spec.js
- server/services/cms.js
https://trello.com/c/1uu7BDVA
To introduce JSON API next episode functionality
> Enable json api next episode switch

- server/app.js
https://trello.com/c/7pf7X6K0
Removing ping and resources from sentry stats and adding sampling so we only send 25% of all requests. 
This should help our usage.
We can't test this in a dev environment so will have to push it to staging and give it a go there.
> Adding error sampling

- server/app.js
bodged this earlier
Need || rather than && !
> Exclude assets and ping

- server/app.js
trimming health requests from those sent to sentry
> Removing health from sentry sampling (we don't have a ping)

- server/app.js
- server/repositories/cmsApi.js
https://trello.com/c/UmcLRNoN
As below
> Error reporting improvements

- server/content/establishmentData.json
- server/routes/__tests__/profile.spec.js
- server/views/pages/profile.html
https://trello.com/c/RehSBZ6F
Removing profile from Berwyn as users cannot authenticate.
> Removing profile from berwyn

- server/app.js
- server/auth/middleware.js
- server/middleware/__tests__/configureEstablishment.spec.js
- server/middleware/configureEstablishment.js
- server/utils/index.js
Also adding new test prisoners
Fixing establishment check
no - little bit of tidy up of old location handling
> Bit of tidy up of establishment handling

- server/content/establishmentData.json
- server/middleware/configureEstablishment.js
- server/routes/__tests__/homepage.spec.js
- server/routes/homepage.js
- server/utils/index.js
- server/views/pages/home.html
No ticket - addressing some tech debt to help aid  the move to single URL.
Moving the home page over to use establishment name rather than establishment ID
n/a
> Moving to use establishment name rather establishment ID for home page

- helm_deploy/prisoner-content-hub-frontend/values-development.yaml
Moving to new cluster
Swapping ingress over to green and removing references to old cluster
This should only be merged once kubectl env vars updated in circle
> Moving dev over to new cluster

- assets/images/icons/icon_external_website.svg
- assets/sass/components/_category.scss
- assets/sass/components/_home-content.scss
- server/repositories/cmsQueries/__tests__/homePageQuery.spec.js
- server/repositories/cmsQueries/__tests__/secondaryTagHeaderPageQuery.spec.js
- server/repositories/cmsQueries/__tests__/secondaryTagPageQuery.spec.js
- server/repositories/cmsQueries/__tests__/seriesHeaderPageQuery.spec.js
- server/repositories/cmsQueries/__tests__/seriesPageQuery.spec.js
- server/utils/__tests__/jsonApi.spec.js
- server/utils/jsonApi.js
- server/views/components/content-tile-large/template.njk
- server/views/components/content-tile-small/template.njk
- server/views/components/related-content/template.njk
- server/views/components/suggested-content/template.njk
https://trello.com/c/ZE9R38Ax
To display new external links content type in the F/E when that is shared from Drupal
Attached to above Trello card
To be merged with create interstitial page work
https://trello.com/c/4omUtyZk
> create external link tile

- assets/sass/components/_page-navigation.scss
- server/routes/__tests__/tags.spec.js
- server/views/components/related-content/template.njk
> Addressing PR comments

- package-lock.json
https://trello.com/c/VJFjveB1
In response to CVE-2022-0155 and potential 'Exposure of sensitive information in follow-redirects
> vulnerability-dependency-update/2022-0155

- README.md
- e2e/cypress/features/profile.feature
- e2e/cypress/mockApis/prisonApi.js
- e2e/cypress/support/step_definitions/profile.js
- e2e/package-lock.json
- e2e/package.json
- server/auth/middleware.js
- server/repositories/__tests__/offenderRepository.spec.js
- server/repositories/offender.js
- server/services/__tests__/offenderService.spec.js
- server/services/offender/index.js
- server/services/offender/responses/__tests__/nextVisit.spec.js
- server/services/offender/responses/nextVisit.js
https://trello.com/c/ZVvS0aCe
The previous endpoint returned all visits order by descending creation time - so we could potentially show a future visit rather than the next one. 
This calls the next visit endpoint which is more suitable
Previously we were showing the 5th of February one and now are correctly showing the 30th of January:
The visit count is 0 as this prisoner hasn't been set up correctly - it works for other  prisoners
Requires release of prison api for DCS-1413
> Fix issue with showing wrong visit data

- server/content/establishmentData.json
https://trello.com/c/XKVHleJi
https://trello.com/c/Z2JkW5Fd
Update Berwyn and Cookham Wood popular topics links
> Update popular topics

- assets/sass/components/_topics.scss
- server/__tests__/app.spec.js
- server/content/knownPages.json
- server/middleware/retrieveTopicList.js
- server/repositories/cmsQueries/__tests__/topicsQuery.spec.js
- server/repositories/cmsQueries/topicsQuery.js
- server/routes/__tests__/homepage.spec.js
- server/routes/__tests__/profile.spec.js
- server/routes/__tests__/topics.spec.js
- server/routes/index.js
- server/routes/topics.js
- server/utils/__tests__/index.spec.js
- server/utils/index.js
- server/views/components/footer/macro.njk
- server/views/components/footer/template.njk
- server/views/components/template.njk
- server/views/components/topics/template.njk
- server/views/pages/topics.html
https://trello.com/c/o3MMYeGZ
Move topics page over to just show topics rather than tags. 
Do not display description:
Will need to follow up to change content types to topics.
> Updating topics page

- assets/sass/_general.scss
- server/content/establishmentData.json
- server/content/knownPages.json
- server/routes/__tests__/help.spec.js
- server/routes/help.js
- server/routes/index.js
- server/utils/__tests__/index.spec.js
- server/utils/index.js
- server/views/components/feedback-widget/template.njk
- server/views/pages/tags.html
- server/views/pages/tagsCategories.html
- test/test-helpers.js
https://trello.com/c/uus51bJP
New content needs to go into the feedback mechanism so that:
Users are signposted to how to ask for support article before leaving comment
> Update feedback component

- assets/javascript/games/mimstris/main.js
- server/views/pages/games/mimstris.html
https://trello.com/c/dJMChzf4
Updated controls to enable Mimstris to be played using arrow keys as well as WASD keys as per user feedback
> Update mimstris controls

- server/repositories/cmsQueries/__tests__/categoryCollectionsQuery.spec.js
- server/repositories/cmsQueries/categoryCollectionsQuery.js
Reverts ministryofjustice/prisoner-content-hub-frontend#474
> Revert "Moving to use new endpoint for sub terms"

- server/repositories/cmsQueries/__tests__/categoryCollectionsQuery.spec.js
- server/repositories/cmsQueries/categoryCollectionsQuery.js
This reverts commit cbbd434748df4332da7f028fe376c272f8f05a1d.
> Revert Revert DCS-1589 Adding token store (#474) (#476)

- server/repositories/cmsQueries/__tests__/homepageContentQuery.spec.js
- server/repositories/cmsQueries/homepageContentQuery.js
Fixing issue in previous ticket
no
updated unit test and query.
n/a
> 1077 fix missing images

- .circleci/config.yml
- helm_deploy/prisoner-content-hub-frontend/templates/_envs.tpl
- helm_deploy/prisoner-content-hub-frontend/templates/secret.yaml
https://trello.com/c/hYLu5kY0/1758-add-a-new-environment-variable-to-enable-the-correct-visitors-api-to-be-queried
No.
- Added the prisonerContactRegisteryApi environment variable into the FE application codebase - helm_deploy > prisoner-content-hub-frontend > templates > secret.yaml
- Added the prisonerContactRegisteryApi environment variable into the FE application codebase - .circleci > config.yml
- Added the PRISONER_CONTACT_REGISTERY_BASE_URL environment variable / code block into the FE application codebase - helm_deploy > prisoner-content-hub-frontend > templates > _envs.tpl
- Added the …
> Add environment variable and config

- helm_deploy/prisoner-content-hub-frontend/values-staging.yaml
Enabling this feature in staging - https://trello.com/c/OLyY02WG/1785-update-approved-visitors-related-views-to-reflect-the-updated-designs
No
Enabled the feature in staging by updating the feature flag for that environment.
No.
No.
No.
> Toggle feature flag

- README.md
No, issue spotted as a new start running the app locally, no need for a ticket.
None.
No
No.
No.
> Update README.md to reflect starting app for dev

- package-lock.json
- package.json
No
All dev dependencies updated to latest versions. Dev dependencies are not used in the actual application so will not cause issues with that.
> Update all dev dependencies

- helm_deploy/prisoner-content-hub-frontend/values-staging.yaml
no - simple update to enable feature on staging.
no.
- enable feature flag on staging.
no.
no.
no.
> enable feature

- server/repositories/offender.js
No ticket needed, simply adding a query param to filter results requested from the prisoner contacts API.
no.
- Added query param to API call, to request social contacts only.
no.
no.
no.
> Add social filter

- server/repositories/offender.js
no
- Updates a single query param
- 
- remove '' from query param
no
no
no
> Update query param

- server/routes/__tests__/money.spec.js
no - small change to fix failing unit tests
no
- update dates in a number of failing unit tests
no
no
no
> update failing unit tests

- .circleci/config.yml
> Update SSH key

- .circleci/config.yml
> Add missing ssh key

- .gitignore
> Ignore Cypress downloads folder

- README.md
> Null PR to redeploy

- README.md
> Second Null PR

- assets/sass/components/_home-navigation.scss
- e2e/cypress/features/profile.feature.js
- e2e/cypress/features/timetable.feature.js
- server/auth/middleware.js
- server/content/breadcrumbs.json
- server/content/knownPages.json
- server/routes/__tests__/profile.spec.js
- server/routes/approvedVisitors.js
- server/routes/money.js
- server/routes/profile.js
- server/routes/timetable.js
- server/services/__tests__/offenderService.spec.js
- server/services/offender/responses/__tests__/nextVisit.spec.js
- server/services/offender/responses/__tests__/timetableEvent.spec.js
- server/services/offender/responses/timetable.js
- server/utils/enums.js
- server/views/components/personal-schedule-one-day/template.njk
- server/views/components/personal-schedule-today/template.njk
- server/views/components/personal-transactions-help/template.njk
- server/views/pages/profile.html
content updates
https://trello.com/c/zHRfKtEK/1906-content-updates-to-my-profile
n/a
Various content updates within the homepage and my profile sections
Update of several supporting unit tests
no
no
no
> Content updates

- package-lock.json
- package.json
- server/clients/baseClient.js
- server/clients/jsonApiClient.js
- test/mockServer.js
> Remove internal axios dependencies and upgrade axios

- helm_deploy/prisoner-content-hub-frontend/templates/_envs.tpl
- helm_deploy/prisoner-content-hub-frontend/values-development.yaml
- helm_deploy/prisoner-content-hub-frontend/values-production.yaml
- helm_deploy/prisoner-content-hub-frontend/values-staging.yaml
- server/config.js
- server/routes/profile.js
- server/views/pages/profile.html
https://trello.com/c/7NIm6NBh/1998-adjudications-2-add-adjudications-feature-flag-and-establishment-flag
no.
- Added feature flag 
- Added establishment restriction flag
- Added place holder adjudications section on the My Profile page behind the feature flag 
No.
No.
No.
> add env variables for feature toggle and test condition in view

- helm_deploy/prisoner-content-hub-frontend/values-staging.yaml
related to this card, - 
no
- minor change to enable feature on staging
no
no
no
> toggle feature on for staging

- server/services/offender/responses/__tests__/adjudication.spec.js
- server/utils/__tests__/adjudication.spec.js
- server/utils/adjudication.js
- server/views/components/personal-adjudication-detail-hearing/template.njk
This is a minor update to the previous PR related to this ticket: https://trello.com/c/BeSENiM4/2033-adjudications-5-adjudications-detail-page
No.
- Updated field name from startDate to effectiveDate to match the data structure. 
- Updated supporting unit tests
No.
No.
No.
> Update hearing startDate to effectiveDate

- helm_deploy/prisoner-content-hub-frontend/values-production.yaml
https://trello.com/c/jUo3jzo2/2055-enable-adjudications-feature-in-production
No.
- Set adjudications feature flag to true, to enable the feature in production.
No.
No.
No.
> Enable adjudications feature in production

- server/routes/adjudications.js
- server/utils/__tests__/pagination.js
- server/utils/pagination.js
No. Bug fixes.
No.
Bug fixes for:
- missing user object
- pagination data being incorrect type
- displays on page error message in both cases instead of the generic 'There was a problem' page.
no
no
> Fix/handle missing user object and handle incorrect data typeError

- server/app.js
> Fix passprtjs

- package-lock.json
- package.json
> Upgrade Jsona module

- Dockerfile
No
Dockerfile was using a node 16 image for the second stage build.
No
> Fix Dockerfile for node18

- server/app.js
No
NA
Reducing Sentry Transaction Sampling from 50% to 5% (the previous PR was intended to do this)
No
No
No
NA
> Refactor Sentry Transaction Sampling from 50% to 5%

- .circleci/config.yml
> Allow branches to staging

- helm_deploy/prisoner-content-hub-frontend/templates/_envs.tpl
- helm_deploy/prisoner-content-hub-frontend/values-development.yaml
- helm_deploy/prisoner-content-hub-frontend/values-local.yaml
- helm_deploy/prisoner-content-hub-frontend/values-production.yaml
- helm_deploy/prisoner-content-hub-frontend/values-staging.yaml
- server/config.js
- server/utils/nunjucksSetup.js
- server/views/components/basicTemplate.njk
- server/views/pages/externalLink.html
https://trello.com/c/Hg7E99MY/2153-add-google-tag-manager-code-blocks-to-the-frontend-application
- Add Google Tag manager to the frontend application
No.
No.
No.
> Add Google Tag Manager scripts

- .circleci/config.yml
- e2e/test-ci.env
- helm_deploy/prisoner-content-hub-frontend/readme.md
- helm_deploy/prisoner-content-hub-frontend/secrets.example.yaml
- helm_deploy/prisoner-content-hub-frontend/templates/_envs.tpl
- helm_deploy/prisoner-content-hub-frontend/templates/secret.yaml
- server/clients/__tests__/adjudicationsApiClient.spec.js
- server/clients/adjudicationsApiClient.js
- server/config.js
- server/repositories/__tests__/offenderRepository.spec.js
- server/repositories/offender.js
- server/routes/adjudications.js
- server/services/index.js
- server/services/offender/index.js
- server/services/offender/responses/__tests__/adjudications.spec.js
- server/services/offender/responses/adjudications.js
https://dsdmoj.atlassian.net/browse/NN-5364
https://dsdmoj.atlassian.net/browse/NN-5366
> NN-5364 NN-5366: get adjudication data from AdjudicationsAPI instead of PrisonAPI

- .github/pull_request_template.md
- helm_deploy/prisoner-content-hub-frontend/values.yaml
> LNP-277: Add Woodhill shortname to ingress

- server/repositories/cmsQueries/__tests__/basicPageQuery.spec.js
- server/repositories/cmsQueries/basicPageQuery.js
No. Problem is to fix https://ministryofjustice.sentry.io/issues/4040583297/?project=5377056&query=is%3Aunresolved&referrer=issue-stream&stream_index=1
> Fix possible missing fieldMainBodyContent attribute

- server/content/establishmentData.json
https://dsdmoj.atlassian.net/browse/LNP-279
n/a
- Added config for HMP Woodhill
No.
No.
No.
> Add HMP Woodhill config

- e2e/cypress/mockApis/incentivesApi.js
- server/repositories/offender.js
> Change incentives endpoint

- server/config.js
- server/repositories/__tests__/offenderRepository.spec.js
- server/repositories/offender.js
- server/routes/adjudications.js
- server/services/index.js
- server/services/offender/responses/__tests__/adjudications.spec.js
- server/services/offender/responses/adjudications.js
https://dsdmoj.atlassian.net/browse/LNP-522
Reverts adjudications to use Prison API
No
> Revert the use of Adjudications API

- server/routes/__tests__/money.spec.js
No.
Fix failing tests, move timers as suggested by @LucasCairns and switch back test data as everything now 2021.
> Fix date-based money tests

- helm_deploy/prisoner-content-hub-frontend/values.yaml
https://dsdmoj.atlassian.net/browse/LNP-611
NA
Adding prison's short name in ingress
NA
NA
NA
> Adding prison's short name alphabetically in ingress

- .circleci/config.yml
No
Not an issue
Updates the Slack alerting channels for content hub frontend releases, issues etc.
No
> Update alert channels to use launchpad alerts

- helm_deploy/prisoner-content-hub-frontend/values.yaml
[LNP-691](https://dsdmoj.atlassian.net/browse/LNP-691)
No
Added prison short name 
No
No
No
[LNP-691]: https://dsdmoj.atlassian.net/browse/LNP-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LNP-691-Adding-prison-short-name-to-ingress

- server/content/establishmentData.json
[LNP-692](https://dsdmoj.atlassian.net/browse/LNP-692)
No
Added custom config like id, machine name etc for bullingdon prison
No
No
No
[LNP-692]: https://dsdmoj.atlassian.net/browse/LNP-692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LNP-692-adding-bullingdon-custom-config

- server/utils/index.js
> Add debug to updateSessionEstablishment

- assets/javascript/games/2048/sass/main.scss
- assets/javascript/games/anagramica/sass/style.scss
- assets/javascript/games/sn4ke/main.css
- server/auth/middleware.js
- server/utils/index.js
404s being shown in AppInsights for incorrectly included SCSS.
> LNP-773: Feature/fix failed govuk scss calls

- server/views/components/basicTemplate.njk
Yes
Appends ` - Content Hub` to all page titles.
> LNP-806: Prefix all page title with Content Hub -

- server/content/establishmentData.json
https://dsdmoj.atlassian.net/browse/LNP-807
N/A
Change the configuration of Cookham Wood in the front end now that it is to become an adult prison.
No
No
No - the corresponding Drupal change has already been done on production.
> LNP-807: 🔧  change Cookham Wood to be an adult prison.

- assets/javascript/govukFrontendInit.js
- assets/javascript/mojFrontendInit.js
- assets/sass/components/_category.scss
- assets/sass/components/_content-tile-large.scss
- assets/sass/pages/flat-content.scss
- bin/build-css
- package-lock.json
- package.json
- server/app.js
- server/utils/nunjucksSetup.js
- server/views/components/basicTemplate.njk
- server/views/pages/adjudication.html
- server/views/pages/adjudications.html
- server/views/pages/approvedVisitors.html
- server/views/pages/category.html
- server/views/pages/externalLink.html
- server/views/pages/profile.html
NA
https://github.com/alphagov/govuk-frontend/releases/tag/v5.0.0
https://github.com/ministryofjustice/moj-frontend/releases/tag/v2.0.0
https://github.com/ministryofjustice/moj-frontend/releases
NA
https://frontend.design-system.service.gov.uk/changes-to-govuk-frontend-v5/#changes-to-gov-uk-frontend-v5-0-0
NA
[LNP-810]: https://dsdmoj.atlassian.net/browse/LNP-810?atlOrigin=eyJpIjoiNWRkNTlj …
> LNP-810-updating-govuk-and-moj-frontend-to-major-version

- package-lock.json
- package.json
NA
This PR includes **only minor or patch updates** for node modules.
NA
NA
NA
[LNP-810]: https://dsdmoj.atlassian.net/browse/LNP-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LNP-810-minor-patch-updates

- package-lock.json
- package.json
NA
This PR includes major version updates to uuid and supertest
NA
NA
NA
[LNP-810]: https://dsdmoj.atlassian.net/browse/LNP-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LNP-810-update-uuid-supertest-major-version

- package-lock.json
- package.json
- server/routes/money.js
NA
This PR includes date-fns update to major version
NA
NA
NA
[LNP-810]: https://dsdmoj.atlassian.net/browse/LNP-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LNP-810-date-fns-to-3

- package-lock.json
- package.json
NA
This PR includes updating eslint-plugin-cypress to 3
NA
NA
NA
[LNP-810]: https://dsdmoj.atlassian.net/browse/LNP-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LNP-810-eslint-plugin-cypress-to-3

- package-lock.json
- package.json
- server/__tests__/app.spec.js
- server/app.js
- server/instrument.js
NA
This PR upgrades '@sentry/node' from version 7 to version 8. The key changes introduced by this upgrade include deprecated features, breaking changes etc.
NA
https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#upgrading-from-7x-to-8x
https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md/#3-removal-of-deprecated-apis
https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#transactioncontext-no …
> LNP-810-update-sentry-node-to-8

- assets/javascript/govukFrontendInit.js
- server/views/pages/adjudication.html
- server/views/pages/adjudications.html
- server/views/pages/approvedVisitors.html
- server/views/pages/category.html
- server/views/pages/profile.html
[LNP-847](https://dsdmoj.atlassian.net/browse/LNP-847)
NA
The paths to the js files have been fixed
NA
NA
NA
[LNP-847]: https://dsdmoj.atlassian.net/browse/LNP-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LNP-847-fixing-path-errors

- helm_deploy/prisoner-content-hub-frontend/values.yaml
- server/content/establishmentData.json
LNP-864
N/A
Make Chelmsford hub unavailable
Removes Chelmsford from establishment data and ingress.
No
No
No
> LNP-864: 🪄  hide Chelmsford.

- helm_deploy/prisoner-content-hub-frontend/values-production.yaml
- helm_deploy/prisoner-content-hub-frontend/values-staging.yaml
> Disable approved visitors

- helm_deploy/prisoner-content-hub-frontend/values.yaml
- server/content/establishmentData.json
LNP-866
N/A
Make Chelmsford hub available
Adding (reverting) Chelmsford to establishment data and ingress.
No
No
No
> LNP-866: Enable Chemlsford Content Hub

- e2e/cypress/mockApis/drupalData/urgentBanners.json
- server/repositories/cmsQueries/__tests__/categoryContentQuery.spec.js
- server/repositories/cmsQueries/categoryContentQuery.js
https://dsdmoj.atlassian.net/browse/LNP-943
N/A
Removes unnecessary filter.
No
No
No
> LNP-943: 🔥  remove field_not_in_series filter when querying for content within a category

- package-lock.json
https://dsdmoj.atlassian.net/browse/LNP-953
N/A
Updates Axios to 1.7.4 to fix security issue.
No
No
No
> LNP-953_update_axios

- package-lock.json
https://dsdmoj.atlassian.net/browse/LNP-971
N/A
Ups micromatch to non-vulnerable version.
No
No
No
> LNP-971: 🔒  update micromatch to 4.0.8.

- helm_deploy/prisoner-content-hub-frontend/values.yaml
https://dsdmoj.atlassian.net/browse/LNP-958
No
Added prison short name
No
No
No
> LNP-958-adding-prison-short-name-to-ingress

- server/content/establishmentData.json
https://dsdmoj.atlassian.net/browse/LNP-960
No
Adding prison custom config
No
No
No
> LNP-960-adding-prison-custom-config

- server/config.js
> LNP-985: Enable profile in Cardiff

- server/config.js
- server/repositories/offender.js
> LNP-992: Update endpoint to use for approved social visitors

- package-lock.json
- package.json
> Update dependencies 2024-10-09

- server/config.js
https://dsdmoj.atlassian.net/browse/LNP-1015
It's just disabling profiles
Disabling sites
No
> LNP-1015: Disable profiles

- .circleci/config.yml
- Dockerfile
- e2e/package-lock.json
- e2e/package.json
- package-lock.json
- package.json
- server/app.js
- server/middleware/configureEstablishment.js
> LNP-1022: Update dependencies 2024-10-21

- package.json
https://dsdmoj.atlassian.net/browse/LNP-1079
N/A
Adds a debug script to package.json, so that local developers can
`npm run debug`
and then attach an IDE to node to perform step debugging
No
No
No
> LNP-1079: add debug script to allow step debugging from IDE.

- e2e/package-lock.json
- e2e/package.json
- package-lock.json
- package.json
https://dsdmoj.atlassian.net/browse/LNP-1085
> LNP-1085: Update dependencies 2024-11-29

- package-lock.json
- package.json
> Update dependencies 2024-12-19

- .circleci/config.yml
> Add approval for deploy feature branch to dev

- assets/sass/components/_topbar.scss
- package-lock.json
- package.json
- server/app.js
- server/config.js
- server/locales/cy.json
- server/locales/en.json
- server/middleware/__tests__/configureEstablishment.spec.js
- server/middleware/configureEstablishment.js
- server/routes/__tests__/homepage.spec.js
- server/utils/nunjucksSetup.js
- server/views/components/basicTemplate.njk
- server/views/components/search/template.njk
- server/views/components/top-bar/macro.njk
- server/views/components/top-bar/template.njk
https://dsdmoj.atlassian.net/browse/LNP-1098
N/A
* Adds i18n and related packages to enable translation
* Updates configuration to list languages per site
* Adds language switcher component to top bar if a site has more than one language
* Configures The Studio to be the only multilingual site (for now)
No
No
No
> LNP-1098: 🏴󠁧󠁢󠁷󠁬󠁳󠁿 language switching

- .circleci/config.yml
- package-lock.json
- package.json
> Update dependencies 2025-01-30

- .circleci/config.yml
> Stop notifying about releases to dev and staging

- e2e/package-lock.json
- e2e/package.json
> Move e2e over to Node 22

- server/middleware/retrieveTopicList.js
- server/routes/__tests__/topics.spec.js
- server/routes/topics.js
https://dsdmoj.atlassian.net/browse/LNP-1130
Browse any page and observe the topics in the footer listed in unalphabetic order.
Browse the /topics page and observe the topics in the footer listed in unalphabetic order.
Sorts the topic list in the frontend app after receiving the response from the back end server.
No
No
No
> LNP-1130 topic ordering

- Dockerfile
> Remove check for unused var in security tests

- server/clients/feedbackClient.js
> Fix error handling when no feedback database

- helm_deploy/prisoner-content-hub-frontend/values-development.yaml
- helm_deploy/prisoner-content-hub-frontend/values-production.yaml
- helm_deploy/prisoner-content-hub-frontend/values-staging.yaml
> Remove single URL ingress

- helm_deploy/prisoner-content-hub-frontend/templates/ingress.yaml
> Remove unused ingress yaml for host

- package-lock.json
> ⬆️  update node_modules/formidable.

- helm_deploy/prisoner-content-hub-frontend/templates/ingress.yaml
- helm_deploy/prisoner-content-hub-frontend/values-staging.yaml
- server/middleware/__tests__/getEstablishmentFromUrl.spec.js
- server/middleware/getEstablishmentFromUrl.js
> Mirror cert usage in staging from prod

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/LNP-1160
N/A
update hmpps circleci orbs to 11.
No
No
No
> LNP_1160: ⬆️  update hmpps circleci orbs to 11.

- package-lock.json
https://dsdmoj.atlassian.net/browse/LNP-1210
N/A
Updates all dependent modules 
No
No
No
> LNP-1210_update_dependencies

- package-lock.json
- package.json
- renovate.json
- server/routes/homepage.js
> Revert jsona update
